- name: Configure bond0 interface
  template:
    src: ifcfg-bond0.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-bond0
    owner: root
    group: root
    mode: 0644

- name: Configure physical interface eth1 for bonding
  template:
    src: ifcfg-eth1.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-eth1
    owner: root
    group: root
    mode: 0644

- name: Configure physical interface eth2 for bonding
  template:
    src: ifcfg-eth2.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-eth2
    owner: root
    group: root
    mode: 0644

- name: Restart NetworkManager to apply bond configuration
  service:
    name: NetworkManager
    state: restarted
