- name: Install packages on RedHat-based systems
  yum:
    name:
      - vim
      - nano
      - traceroute
      - tcpdump
      - net-tools
    state: present
    update_cache: true
  when: ansible_os_family == "RedHat"

- name: Install packages on Debian-based systems
  apt:
    name:
      - vim
      - traceroute
      - tcpdump
      - net-tools
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"
